services:
  go:
    build: ./
    container_name: go-container
    volumes:
    - ./:/app
    ports:
    - "8080:8080"
    tty: true
    networks:
      - back-db
  db:
    image: mysql
    container_name: db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    networks:
      - back-db
    volumes:
      - go-api-data:/var/lib/mysql
    
volumes:
  go-api-data:

networks:
  back-db:
    name: back-db
    driver: bridge