services:
  go:
    build: ./
    container_name: go-container
    volumes:
    - ./:/app
    working_dir: /app
    ports:
    - "8080:8080"
    tty: true
    networks:
      - back-db
  db:
    image: mysql
    container_name: db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: develop
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - back-db
    volumes:
      - go-api-data:/var/lib/mysql
    
volumes:
  go-api-data:

networks:
  back-db:
    name: back-db
    driver: bridge